image: alpine/edge
packages:
  - git
  - nodejs
  - npm
secrets:
  - bce89f30-642f-422c-b7f9-08e655b447aa
  - bfb68f29-f23e-4733-85a2-a3c19c0bb729
  - eeb496e6-af72-40d1-b4b0-94878c7f6c66
tasks:
  - npm-setup: |
      echo "npm user:"
      npm whoami
  - git-setup: |
      git clone git@github.com:codsen/codsen
      cd codsen
      git remote set-url origin git@github.com:codsen/codsen
      ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
      echo "git user:"
      git config user.name
      git status
      git checkout main
  - bootstrap: |
      cd codsen
      npm run fresh
  - readme: |
      cd codsen
      npm run info
      npm run readme:generate
  - first-git-add: |
      cd codsen
      pwd
      git status
      npx lerna changed
