
#
#    C O D S E N
#

deploy:
  except:
    - tags
  image: node:latest
  stage: deploy
  script:
    - git config --global credential.helper store
    - git remote set-url origin https://gitlab-ci-token:$PERSONAL_ACCESS_TOKEN@gitlab.com/codsen/codsen.git
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$YOUR_NAME_SURNAME"
    - npm set unsafe-perm true -g
    - npm set //registry.npmjs.org/:_authToken $NPM_TOKEN -g
    - npm set username $NPM_USERNAME -g
    - npm set email $NPM_EMAIL -g
    - echo "git user:"
    - git config user.name
    - echo "npm user:"
    - npm whoami
    - set -o pipefail
    - echo '█████████████████████████████ 1 █████████████████████████████'
    - git status
    - git checkout master
    - echo '█████████████████████████████ 2 █████████████████████████████'
    - git status
    - npm run fresh
    - echo '█████████████████████████████ 3 █████████████████████████████'
    - git status
    - npm run readme:generate
    - echo '█████████████████████████████ 4 █████████████████████████████'
    - git status
    - git add packages
    - git add stats
    - git add README.md
    - "git add package-lock.json || echo 'no package-lock.json'"
    - "git diff-index --quiet HEAD || git commit -m '[skip ci] chore: automated build tasks' --no-verify"
    - npm run pub:vers
    - echo '█████████████████████████████ 5 █████████████████████████████'
    - git status
    - git add packages
    - git add README.md
    - echo '█████████████████████████████ 6 █████████████████████████████'
    - git status
    - "git commit -m '[skip ci] chore: automated build tasks' --no-verify"
    - echo '█████████████████████████████ 7 █████████████████████████████'
    - git status
    - npm run republish
    - echo '█████████████████████████████ 8 █████████████████████████████'
    - git status
    - git push origin master
    - echo '█████████████████████████████ 9 █████████████████████████████'
    - "curl https://purge.jsdelivr.net/npm/detergent/dist/detergent.umd.js || echo 'detergent unreachable on jsdelivr'"
    - "curl https://purge.jsdelivr.net/npm/html-crush/dist/html-crush.umd.js || echo 'html-crush unreachable on jsdelivr'"
    - "curl https://purge.jsdelivr.net/npm/email-comb/dist/email-comb.umd.js || echo 'email-comb unreachable on jsdelivr'"
    - "curl https://purge.jsdelivr.net/npm/string-strip-html/dist/string-strip-html.umd.js || echo 'string-strip-html unreachable on jsdelivr'"
    - "curl https://purge.jsdelivr.net/npm/emlint/dist/emlint.umd.js || echo 'emlint unreachable on jsdelivr'"
    - "curl https://purge.jsdelivr.net/npm/codsen-tokenizer/dist/codsen-tokenizer.umd.js || echo 'codsen-tokenizer unreachable on jsdelivr'"
    - "curl https://purge.jsdelivr.net/npm/codsen-parser/dist/codsen-parser.umd.js || echo 'codsen-parser unreachable on jsdelivr'"
    - "curl https://purge.jsdelivr.net/npm/json-variables/dist/json-variables.umd.js || echo 'json-variables unreachable on jsdelivr'"
    - echo '█████████████████████████████ 10 ████████████████████████████ - done'
