
#
#    C O D S E N
#

before_script:
  - git remote set-url origin https://oauth2:$PERSONAL_ACCESS_TOKEN@gitlab.com/codsen/codsen.git
  - git config --global user.email $GITLAB_USER_EMAIL
  - git config --global user.name $YOUR_NAME_SURNAME

deploy:
  image: node:latest
  stage: deploy
  script:
    - git status
    - echo '//registry.npmjs.org/:_authToken=$NPM_TOKEN\nusername=$NPM_USERNAME\nemail=$NPM_EMAIL' > ~/.npmrc
    - npm whoami
    - git config user.name
