
#
#    C O D S E N
#

before_script:
  - git remote set-url origin https://oauth2:$PERSONAL_ACCESS_TOKEN@gitlab.com/codsen/codsen.git
  - git config --global user.email $GITLAB_USER_EMAIL
  - git config --global user.name $YOUR_NAME_SURNAME

deploy:
  image: node:latest
  stage: deploy
  script:
    - git status
    - git config user.name
    - npm set unsafe-perm true -g
    - npm set //registry.npmjs.org/:_authToken $NPM_TOKEN -g
    - npm set username $NPM_USERNAME -g
    - npm set email $NPM_EMAIL -g
    - npm whoami
