# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - packages/

deploy:
  image: node:latest
  stage: deploy
  script:
    - git checkout FETCH_HEAD
    - git status
