# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - packages/

before_script:
  - git remote set-url origin https://oauth2:${PERSONAL_ACCESS_TOKEN}@gitlab.com/codsen/codsen.git
  - git config --global user.email ${GITLAB_USER_EMAIL}
  - git config --global user.name ${GITLAB_USER_NAME}

deploy:
  image: node:latest
  stage: deploy
  script:
    - git status
    - git checkout master
    - echo '5'
    - npm run bootstrap
    - echo '6'
    - npm run all:test:full
    - echo '7'
    - npm run readme:generate
    - echo '8'
    - npm run pub:vers
    - echo '9'
    - git add packages
    - echo '10'
    - git status
    - "git commit -m '[skip ci] chore: Automated build tasks' --no-verify"
    - echo '11'
    - git status
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - echo '12'
    - git status
    - npm run republish
    - echo '13'
    - git push origin master
    - echo '14 - done'
