
#
#    C O D S E N
#

before_script:
  - git remote set-url origin https://oauth2:${PERSONAL_ACCESS_TOKEN}@gitlab.com/codsen/codsen.git
  - git config --global user.email ${GITLAB_USER_EMAIL}
  - git config --global user.name ${GITLAB_USER_NAME}

deploy:
  image: node:latest
  stage: deploy
  script:
    - git status
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}\nusername=${NPM_USERNAME}\nemail=${NPM_EMAIL}' > .npmrc
    - echo '1'
    - git status
    - git checkout master
    - echo '2'
    - git status
    - npm run bootstrap
    - echo '3'
    - git status
    - npm run all:test:only
    - echo '4'
    - git status
    - npm run readme:generate
    - echo '5'
    - git status
    - npm run pub:vers
    - echo '6'
    - git status
    - git add packages
    - echo '7'
    - git status
    - "git commit -m '[skip ci] chore: Automated build tasks' --no-verify"
    - echo '8'
    - git status
    - npm run republish
    - echo '9'
    - git status
    - git push origin master
    - echo '10 - done'
