# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - packages/

deploy:
  image: node:latest
  stage: deploy
  script:
    - npm run bootstrap
    - npm run build:just
    - npm run all:test:only
    - npm run pub:vers
    - npm run readme:generate
    - git add packages
    - "git commit -m 'chore: Automated build tasks' --no-verify"
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm run republish
