
#
#    C O D S E N
#

deploy:
  except:
    - tags
  image: node:latest
  stage: deploy
  script:
    - git config --global credential.helper store
    - git remote set-url origin https://gitlab-ci-token:$PERSONAL_ACCESS_TOKEN@gitlab.com/codsen/codsen.git
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$YOUR_NAME_SURNAME"
    - npm set unsafe-perm true -g
    - npm set //registry.npmjs.org/:_authToken $NPM_TOKEN -g
    - npm set username $NPM_USERNAME -g
    - npm set email $NPM_EMAIL -g
    - echo "git user:"
    - git config user.name
    - echo "npm user:"
    - npm whoami
    - echo '█████████████████████████████ 1 █████████████████████████████'
    - git status
    - git checkout master
    - echo '█████████████████████████████ 2 █████████████████████████████'
    - git status
    - npm run bootstrap
    - echo '█████████████████████████████ 3 █████████████████████████████'
    - git status
    - make build-test
    - echo '█████████████████████████████ 4 █████████████████████████████'
    - git status
    - npm run readme:generate
    - echo '█████████████████████████████ 5 █████████████████████████████'
    - git status
    - git add packages
    - git add readme.md
    - "git diff-index --quiet HEAD || git commit -m '[skip ci] chore: Automated build tasks' --no-verify"
    - npx lerna changed
    - echo '█████████████████████████████ 6 █████████████████████████████'
    - npx lerna version --conventional-commits --no-commit-hooks --no-push --yes
    - echo '█████████████████████████████ 7 █████████████████████████████'
    - npx lerna-clean-changelogs-cli '**'
    - echo '█████████████████████████████ 8 █████████████████████████████'
    - git status
    - git add packages
    - git add readme.md
    - echo '█████████████████████████████ 9 █████████████████████████████'
    - git status
    - "git diff-index --quiet HEAD || git commit -m '[skip ci] chore: Automated build tasks' --no-verify"
    - echo '█████████████████████████████ 10 █████████████████████████████'
    - git status
    - npm run republish
    - echo '█████████████████████████████ 11 █████████████████████████████'
    - git status
    - git push origin master
    - echo '█████████████████████████████ 12 █████████████████████████████ - done'
