# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - packages/

before_script:
  - npm run bootstrap
  - npm run build:just
  - npm run readme:generate

unit test:
  image: node:latest
  stage: test
  script:
    - npm run all:test:only

deploy:
  image: node:latest
  stage: deploy
  script:
    - lerna version --conventional-commits --yes
    - lernacleanchangelog "**"
    - npm run readme:generate
    - git add packages
    - git commit -m 'chore: Automated build tasks' --no-verify
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm run republish
