language: node_js
node_js:
  - '6'
before_install:
# package-lock.json was introduced in npm@5
- npm install -g npm@5 # skip this if you are using node 9
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
notifications:
  email:
    on_success: never
    on_failure: change
after_success: npm run coverage
