node_js:
  - 6
before_install:
- npm install -g npm
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
# Only the node version 6 job will upload the lockfile
after_script: greenkeeper-lockfile-upload
notifications:
  email:
    on_success: never
    on_failure: change
after_success: npm run coverage
env:
  global:
    secure: d2m8gGy9xRzmh+TGxvCTe7gQ5NFeQ1ZyNAjb+DLarNXmyzXMqkbIwVtwT6UlQzvyj1BFDNwMQ8hAKlEVMqf1DgXH2NDNnS6TppC7ldX3kfJjMTReFhhvKLLooobdookHO7XIL9kLTY9OsmlX5gyWOWPBagFTHbDx6u6o0UanfVFG8fcKu8T9fAbZiJwDmobdSwpAH3hzJ3UV23MgsAItsM1GZIDrJ9nUmI4AyGiPRZLZFgbUqjIy1vN4cdlzUUB9wh4ASpQkZYkIBVEplpUq5ndlpbNQL9BTQN5/imEV+F1Dbsr5L9wnzOM1cpqP41olML5Bb/lLrQPaaHR/f0nCnXL4TRJCGOmCe3xw49FML3VHV21Gy3wjTUGV8B3sOXS5LFFF+TbNwat7OpVdcBKBKCM9Dp+zcQbrC4RKSh3EkYJ9r00n4q7MgJzXhz3XfPDJj6DKugmHXkOI0qcIFss2iC0Do7emr8GD/KWe2Yk4O0GBUx/3Xio90AyGLS/IVJU/NGs20ckAuFhMyyqPTNENLGKskYG6uLgNUGzyuI04SLaz2hXD24A+jOmgKms2B1pkIdrlucyKR9qdZco97QwbwrozSpVUgK4Gmr/K9/7lbVONTXDSHkwyJBpsRAeYRe3xfFrLQ76EHdHKRc9kxCwkN0R2R6EXY0gSuM6FGF137zg=
